---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ripple_iff
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ripple_iff
        platform: ripple
    spec:
      containers:
      - name: ripple_iff
        image: mtouloup/ripple_iff
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 51235
        env: