---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripple-iff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ripple-iff
  template:
    metadata:
      labels:
        app: ripple-iff
        platform: ripple
    spec:
      containers:
      - name: ripple-iff
        image: 10.10.70.15:5001/ripple_server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 51235
